### ISSUE TITLE
Don't delete the current tab

### ISSUE THREAD

**Issue by allanwind** [igorlogius/close-duplicate-tabs#2]
When we identify a set of duplicates of a given url we delete all but the oldest tab in the group.  This works great.  We may want handle the current tab as a special case and not delete it.  From UX perspective it's a little surprising, and I think you make the case that the current tab is "more important" than whatever you can't see. It's definitely minor priority, and I am fine if you reject it.  I don't know if current behavior may be preferable to some users, in which, it would point to an option opposed to a straight up change.  What do you think?

**Comment by igorlogius** [comment]
You mean like this => 
https://addons.mozilla.org/firefox/addon/close-other-duplicate-tabs/

**Comment by allanwind** [comment]
"close other duplicate tabs" seems to look at the current tab, and close other others with the same url.  This is not useful to me.  "close all duplicate tabs" looks at all tabs and what I am suggesting is treat the current/active(?) tab as special (like it's always the oldest).

**Comment by igorlogius** [comment]
ah ... now i understand what you mean. My mistake ... 
I have to think a bit about that ... i'll come back to you later.

**Comment by igorlogius** [comment]
I think i could faily easy add a way to ignore the current tab from the deletion. 
But that will mean that when another older tab exists both the older/est and the currently active tab will be keeped.  Making it so that only the current tab is keeped would require quite the rewrite, which to be frank i currently do not have the motivation todo.

**Comment by allanwind** [comment]
Could we overwrite the "created" value for the current tab?  I assume it's the sort() call that figures out which is the ones we keep and which are the ones we deleted.   Don't worry about it if it's a bunch of work as the addon is already brilliant the way it works.

**Comment by igorlogius** [comment]
> Could we overwrite the "created" value for the current tab to always be the oldest?

i think i could kind of invert the rule  
by just retaining the newest/last_accessed tab instead

That should implicitely always keep the currently active tab open.

**Comment by igorlogius** [comment]
You can test it out with `1.0.5` and see if this feels more natural.

**Comment by allanwind** [comment]
I don't that is a good idea, and sorting desc it is also not a fix (open two duplicate tabs, make the oldest tab active).   UX wise, I am thinking what is most valuable to the user and I think it goes like this: current tab > oldest duplicate > newer duplicates.  You are looking at the current tab so that's most valuable, for you may have read half the article of an oldest tab while you just open a duplicate of it so the oldest is most valuable.  If we can't do this easily, then I suggest you revert.

**Comment by igorlogius** [comment]
I can not quite agree with you reasoning ... or rather i see that different poeple depending on their workflow/usecases will have different opinions in this regards. 

At the moment i think i'll be keeping the last activated tabs a the default, since this way the active tab naturally wont be closed.

If you prefer the old way, i can add an option to switch back to the deletion by tab creation time,  but i wont be adding the feature to retain the active tab for that option, since i dont see an good way change the algorithm at the moment.  

We can keep this issue open and mark it with "Help wanted" if you like, then maybe someone will make a PR at one point in the future.

**Comment by allanwind** [comment]
Please add the option to revert to previous behavior.  Sounds good, re "Help wanted".

**Comment by igorlogius** [comment]
![Screenshot_2024-01-15_14-10-21](https://github.com/igorlogius/close-duplicate-tabs/assets/67047467/4ff77a9c-76e4-4506-a389-d99f039499cc)

**Comment by igorlogius** [comment]
Note: this featues has been slightly "enhanced", when the options is now checked, not only the active tabs will be excluded from duplication, but every highlighted tab can be excluded too. 


https://github.com/igorlogius/close-duplicate-tabs/assets/67047467/e49a870d-ca58-459d-a8b1-18e5f34df91d

**Comment by allanwind** [comment]
Awesome.  What is a highlighted tab?

**Comment by igorlogius** [comment]
highlighted, means selected

The active tab is always selected, but you can select/hightlight more tabs, by holding CTRL and clicking on the tab header.


https://github.com/igorlogius/close-duplicate-tabs/assets/67047467/bc3e0ae1-3523-4fd7-b1f7-073352d5937a
