### ISSUE TITLE
icon flashing periodically

### ISSUE THREAD

**Issue by circcc** [igorlogius/close-duplicate-tabs#5]
![aa](https://github.com/igorlogius/close-duplicate-tabs/assets/72944033/9a484429-d5e4-4f87-9586-0f050c807019)

I removed this extension because I was concerned about the hourglass icon flashing periodically in a recent update. It's probably related to periodically checking for duplicate tabs, but I don't know why this is necessary since it only needs to be checked when opening or closing a tab.

**Comment by igorlogius** [comment]
Hi, thanks the report.

i can not quite reproduce the flashing. But that said the icon can potentially be updated each time any tab changes its URL or loading state. (ref. background.js:136)

If you use any kind of other addons which reloads tabs or just use websites which update their url that might explain the unexpected flashing of the icon. 

So my request would be: 

1. please verify that the issue is reproducable in a new second empty profile. 
2. hand over the instructions (or a screencapture) for me to try and reproduce the issue.
 
Having recieved this information i'll try to look further into the issue.

**Comment by igorlogius** [comment]
sure

**Comment by circcc** [comment]
Thanks. Problem solved.
